### ISSUE TITLE
ADD ReDis Support

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/extdb#106]
https://github.com/luca3m/redis3m/blob/master/src/connection_pool.cpp

**Comment by RimBlock** [comment]
Support for MySQL and ReDIS at the same time (ReDIS for caching some data and MySQL for other data for example) ?.

**Comment by Torndeco** [comment]
extDB wont be doing any caching itself, its just different backends you can use.

Also Multiple Concurrent Database Support is coming in.
So you could connect to multiple Servers
SQL Databases MySQL / SQLite 
NoSQL MongoDB / ReDIS (Still need to look over ReDIS but looks good)

**Comment by fiws** [comment]
erm, are we talking about http://redis.io/ ? Because it is never ever written like 'reDIS' or 'ReDis'
go Redis or redis.

**Comment by RimBlock** [comment]
Yep, was thinking more of having ReDis as a store for fairly static data where there is quite a lot of it (ie. traders stock levels and prices) whilst still using MySQL for the core of the persistant data.

Would be a nice addidtion.

**Comment by Torndeco** [comment]
You could look at storing static data in a SQLite Database aswell, it will
envolve less work.

I assume you are working on A2 Epoch etc...
Epoch A3 saves Stock Levels in an array and stores it via setvariable on
the trader AI.
So it only queries for Stock Levels @ Server Startup  unlike A2 Epoch.
But it does sync every trade back to database.
Its just something to be aware of

**Comment by RimBlock** [comment]
This is intended for a new A3 full conversion with strong hints of Stalker, some role playing aspects (perks, stats, specialisations) new map, objects, restricted zones, new factions etc.

It would be good to have a quantity / demand based trading system and ReDis acting as a fast cache for that info would be an advantage to getting it to work reasonibly.  Very early days yet though.  Now DB connectivity is sorted, we can concentrate more on the actual coding and getting the base framework in place.
