### ISSUE TITLE
Connecting to MySQL

### ISSUE THREAD

**Issue by breaup** [Torndeco/extdb#108]
Hey, first of all thanks for your work it makes alot of thing possible! 

My question is, today I updated my arma 3 wasteland server, since I cannot load from the mysql database it seems it reverted back to Inidb. 

in my wasteland config I got A3W_savingMethod = "extDB"; which should do the trick. I am not sure if this is a wasteland problem or extdb problem, see if someone can help me. 

Cheers

**Comment by Torndeco** [comment]
If extDB is running you should be getting extDB logs
You will see them in same directory were you have extDB.so / extDB.dll

Also pastebin your A3Wasteland RPT Logs

**Comment by breaup** [comment]
yeah its probly not running only logs I have is from yesterday :/

**Comment by Torndeco** [comment]
Pastebin your RPT logs anyway and i have a look
I also assume you had extDB running before ?

**Comment by breaup** [comment]
yeah it was running fine this morning before I update. My db has alot of data in it... this is what I have from last logs yesterday

[18:27:10 --3:00] [Thread 2381033462] extDB: Version: 29
[18:27:10 --3:00] [Thread 2381033462] extDB: Found extdb-conf.ini
[18:27:10 --3:00] [Thread 2381033462] extDB: Creating Worker Thread +1
[18:27:10 --3:00] [Thread 2381033462] extDB: Creating Worker Thread +1
[18:27:10 --3:00] [Thread 2381033462] extDB: Database Type: MySQL
[18:27:10 --3:00] [Thread 2381033462] extDB: Database Session Pool Started

**Comment by breaup** [comment]
I also have -mod=@extDB in my launch for the server

**Comment by breaup** [comment]
it's also probly something really obvious I did

**Comment by Torndeco** [comment]
Server RPT logs....   
Logs from yesterday when its working wont tell me anything

**Comment by breaup** [comment]
http://pastebin.com/FpxtKSmA

**Comment by Torndeco** [comment]
To start with thats an Altis Life RPG Server  not a3wasteland
Besides your best off to ask on whichever forums for support etc

**Comment by breaup** [comment]
lol nah it's a wasteland server just did not took off the @life_server off the launch option. 

But I have a post up in the Wasteland forums just waiting on a reply. Thanks for trying tho :)

**Comment by Torndeco** [comment]
You really should disable it
Life Server does actually do afew things even though a script doesnt call
it.
Plus a few functions are compiled final into server memory doing nothing.

https://github.com/TAWTonic/Altis-Life/blob/master/extDB-Build/life_server/config.cpp#L143-L149

https://github.com/TAWTonic/Altis-Life/blob/master/extDB-Build/life_server/config.cpp#L143-L149

**Comment by breaup** [comment]
Yeah when you pointed it out I took it off and re launched the server with
no dice. Just to show you it was working fine
http://breautech.com:90/A3WastelandTools/Pages/Leaderboards starts are up
since yesterday still...

On Wed, Jan 21, 2015 at 8:14 PM, Torndeco <notifications@github.com> wrote:

> You really should disable it
> Life Server does actually do afew things even though a script doesnt call
> it.
> Plus a few functions are compiled final into server memory doing nothing.
>
>
> https://github.com/TAWTonic/Altis-Life/blob/master/extDB-Build/life_server/config.cpp#L143-L149
>
>
> https://github.com/TAWTonic/Altis-Life/blob/master/extDB-Build/life_server/config.cpp#L143-L149
>
> On Thu, Jan 22, 2015 at 12:10 AM, Pierre Breau <notifications@github.com>
> wrote:
>
> > Closed #108 <https://github.com/Torndeco/extdb/issues/108>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Torndeco/extdb/issues/108#event-222718280>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Torndeco/extdb/issues/108#issuecomment-70948573>.
>



-- 
*Pierre Breau*
