### ISSUE TITLE
SQF Files in your repo

### ISSUE THREAD

**Issue by ItsReddi** [Torndeco/extdb#113]
Hi,
just a question.
What are these sqf files in your repository? Do we need it on our Altis Life Server if we are updating?
Or what is the intend of the files?

Thanks

**Comment by Torndeco** [comment]
extDB is made as a general extension for arma engine...
The SQF Files are just examples of how to talk to extDB for mission / addon makers
They are not needed for Altis Life RPG, it has its own SQF Files in the server files
