### ISSUE TITLE
extDB v31 crash.

### ISSUE THREAD

**Issue by RimBlock** [Torndeco/extdb#114]
Just got a crash report from A3.

  extDB (D:\ServerFolders\Epoch Transfer\Epoch Test Servers\Dominion\@extdb\extDB.dll)
Distribution: 0
Version 1.38.128937
Fault time: 2015/01/26 00:27:41
Fault address:  6DBBFCCA 01:001EECCA D:\ServerFolders\Epoch Transfer\Epoch Test Servers\Dominion\@extdb\extDB.dll
file:     Dominion
world:    Altis
Prev. code bytes: 0F 82 68 03 00 00 0F BA 25 AC 50 F9 6D 01 73 07
Fault code bytes: F3 A4 E9 17 03 00 00 81 F9 80 00 00 00 0F 82 CE

Registers:
EAX:00000025 EBX:15F3BEE0
ECX:00000025 EDX:00000025
ESI:00000000 EDI:15F33F10
CS:EIP:0023:6DBBFCCA
SS:ESP:002B:41DFDC84  EBP:15F2FF1C
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010217

Nothing in the extDB log file.

Testing lots of new SQL code for custom v5.  

Let me know what other info you would like.

**Comment by Torndeco** [comment]
Hmm get Skype ;)
Have an idea what might be causing it

Can you reproduce it ?
Be nice to see the whole RPT log for the exception error i.e armaserver normally has error info @ top + bottom of RPT Log.
DB_CUSTOM_V5 file aswell 
thanks

**Comment by Torndeco** [comment]
Nevermind see the issue v32 should work fine.
Made the wrong assumption about why i had a mutex lock 

I will push out a new version later today

**Comment by Torndeco** [comment]
Btw i assume you mean v32 build.
Since v32 has fixes for problems you encountered on the froums

If its actually v30
Would still like to see your RPT / extDB logs / db_custom file etc
You PM them on arma forums or Skype etc

**Comment by Torndeco** [comment]
Yeah i need more info,
I have no idea if that crash happened during SQL Query or loading db_custom file etc...

Steps to reproduce if possible
Full RPT Logs, there is error output for crash split into 2 sections in the log files
DB_CUSTOM File
extDB logs (ideally debug ones)

Get Skype easier to ask questions i.e
Are you using 2 different DB_CUSTOM_V5 Protocols loaded at same time
Is that really v30 ??? considering i fixed some issues + you were using a newer version last i heard on the forums.

**Comment by RimBlock** [comment]
Will check the version when home tonight.  May be v31 but is not the latest.

It appears to be when firing a query.  but the diag log lines I put in (extensively at each stage) are not reporting what query is being fired.  I do have an idea from previous logs where the code may be getting to before crashing and will check and provide feedback later.  I will try to narrow it down and provide you the details in order for you to reproduce.

For the load sequence is it just connected to a db, loading custom_v5 and then locking.  Single DB only, single protocol only.

Have sent a friend request on Skype.  I am guessing you are 8 hours behind me time wise.  I will try to make my messages at acceptible times for your timezone.

**Comment by RimBlock** [comment]
First part of the crash report

=======================================================
-------------------------------------------------------
Exception code: C0000005 ACCESS_VIOLATION at 6DBBFCCA

Version is v31.

Have just tried with a query I suspect may be causing the issue via the test tool (which crashed) and here is the extDB log

[21:30:16 +00:-1] [Thread 2887429959] extDB: Version: 31
[21:30:16 +00:-1] [Thread 2887429959] extDB: Found extdb-conf.ini
[21:30:16 +00:-1] [Thread 2887429959] extDB: Creating Worker Thread +1
[21:30:16 +00:-1] [Thread 2887429959] extDB: Creating Worker Thread +1
[21:30:16 +00:-1] [Thread 2887429959] extDB: Creating Worker Thread +1
[21:30:16 +00:-1] [Thread 2887429959] extDB: Creating Worker Thread +1
[21:30:16 +00:-1] [Thread 2887429959] extDB: Creating Worker Thread +1
[21:30:16 +00:-1] [Thread 2887429959] extDB: Creating Worker Thread +1
[21:30:16 +00:-1] [Thread 2887429959] extDB: Creating Worker Thread +1
[21:30:16 +00:-1] [Thread 2887429959] extDB: Creating Worker Thread +1
[21:31:26 +00:-1] [Thread 2887429959] extDB: Extension Input from Server: 9:DATABASE:DominionDB
[21:31:26 +00:-1] [Thread 2887429959] extDB: Database Type: MySQL
[21:31:26 +00:-1] [Thread 2887429959] extDB: Database Session Pool Started
[21:31:33 +00:-1] [Thread 2887429959] extDB: Extension Input from Server: 9:ADD:DB_CUSTOM_V5:CUSTOM_SQL:Dominion_Custom_v5_Calls
[21:31:33 +00:-1] [Thread 2887429959] extDB: DB_CUSTOM_V5: Loading Template Filename: extDB\db_custom\Dominion_Custom_v5_Calls.ini
[21:32:07 +00:-1] [Thread 2887429959] extDB: Extension Input from Server: 2:CUSTOM_SQL:getLoadoutTierDetails:0
[21:32:07 +00:-1] [Thread 1057879622] extDB: DB_CUSTOM_V5: Trace: Input: getLoadoutTierDetails:0

The SQL is 
;;______________________________________________________________
[GetPlayerRecord]
;;

SQL1_1 = select tier from player_record where playerUID = ?;

Number of Inputs = 1
SQL1_INPUTS = 1-STRING
OUTPUT 1

The create sql for the table is 
CREATE TABLE `player_record` (
  `playerUID` varchar(20) NOT NULL DEFAULT '0',
  `tier` int(2) unsigned NOT NULL,
  `notes` longtext,
  `lastLogin` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`playerUID`),
  UNIQUE KEY `playerUID_UNIQUE` (`playerUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

The data in the table is 
PlayerUID                        Tier  Notes  LastLogin
"76561197970856200"	  0		    2015-01-26 00:06:47

**Comment by RimBlock** [comment]
note the 'notes' field is empty.

**Comment by Torndeco** [comment]
I swear i saw Poco 1.6 throw exceptions for Long Text... 
Looks like i need to put back up the warning :(

--------------------------------------
--------------------------------------

      Type | Maximum length
-----------+-------------------------------------
  TINYTEXT |           255 (2 8−1) bytes
      TEXT |        65,535 (216−1) bytes = 64 KiB
MEDIUMTEXT |    16,777,215 (224−1) bytes = 16 MiB
  LONGTEXT | 4,294,967,295 (232−1) bytes =  4 GiB

Basicly you can;t use LONGTEXT with Poco.
TEXT is good enough for pretty much everything realistically in arma.

For an idea each callExtension is about 10k in retreiving Info.
9:OUTPUTSIZE will tell you the current value, as it different between arma2/3 + can change in patch.

--------------------------------------------------
--------------------------------------------------

Second issue is your OUTPUTS is not working ;P

Its OUTPUT not OUTPUTS, i know its a pain... 
I will look @ putting in extra error catching into DB_CUSTOM Loading

Also don't use x-STRING for anything but a string
For example it 
["Why","wont","this","compile","as","an","array"]
->
"[Why,wont,this,compile,as,an,array]"

STRING Option is basicly only there for a string getting stored in Database.
And to protect against nefarious PlayerName.

**Comment by RimBlock** [comment]
String also seems to be handy in handling datetime data.

So only single strings need the -string but arrays do not need the whole array wrapped in quotes ?.

**Comment by Torndeco** [comment]
Nope, arma will compile that just fine as an array

Like i said -STRING will break Arrays, since it will remove the quotes inside the array

**Comment by RimBlock** [comment]
ok.
