### ISSUE TITLE
Request: New input / Output option "QUOTE" to quote without the strip that String does.

### ISSUE THREAD

**Issue by RimBlock** [Torndeco/extdb#116]
Request for enhancement.
Item
INPUT / OUTPUT added option -QUOTE.  
Reason
Allow the SQL input parameters or output fields to be quoted (add " at each end) to allow for easy management of items we want with quotes for easy compile in SQF back to their ARMA datatypes.

ie.
If I have some SQL that requires 4 input parameters of 

0 (int)
"Dog" (String)
["cat", 0 , 0.436, [17, "fish", "Rabbit", 90], "wet"]
16

If I pass these as an array to the SQF function which is used to create the ext call and param list for it then it will receive;

_this = [0,"Dog",["cat", 0 , 0.436, [17, "fish", "Rabbit", 90], "wet"], 16]

I will then need to go through each element in order to work out which ones are arrays and therefore need quotes.

By adding a QUOTE option in the extDB.ini to quote inputs (without the strip) then I can just say;

INPUT 1, 2, 3, 4-QUOTE, 5

And do not have to do any investigation at an SQF level.

Would have thought it would just be the same as is being done with string but without the strip first so should be pretty easy to implement.

**Comment by Torndeco** [comment]
You don't need to add Quotes to an array to store it in the Database !!!

You do str(_array) or format[%1,_array] to turn it into a string so you can concat strings and send the info to extDB.

By adding Quotes to the array, when you retrieved the result it is no longer an array its a string.
[]  == array
"[]" == string

**Comment by RimBlock** [comment]
Yep, gotcha.  Is working as hoped now.

Thanks
