### ISSUE TITLE
extDB v34 not working on windows server 2012 R2 (AltisLife) since v30

### ISSUE THREAD

**Issue by LucaDev** [Torndeco/extdb#118]
System: Windows Server 2012 R2
extDB version: 34
Problem: extDB not working since version 30 (v29 is working correctly)
Gamemode: AltisLife
Error: 
21:36:09 "extDB: Version: "
21:36:09 "extDB: Error checked extDB/logs for more info"

**Comment by Torndeco** [comment]
Update your extdb-conf.ini
Try again
------------------
Try set
[Main]
Threads = 4

**Comment by LucaDev** [comment]
Not working

**Comment by LucaDev** [comment]
Config: http://pastebin.com/C3zw13WS

**Comment by Torndeco** [comment]
All i can recommend is double check you have updated your tbb + tbbmalloc files
They do change (cant remember the last time i updated them)

Try out the Test Application in a command line window + see if it runs
Without some extDB logfiles i have no idea why its not working for you.

**Comment by LucaDev** [comment]
Problem solved after after reinstalling vcredist
