### ISSUE TITLE
Hardcoded Rcon Ip address

### ISSUE THREAD

**Issue by killerty69** [Torndeco/extdb#124]
One of my server won't be able to use the rcon features because the ip address is hard coded in.

**Comment by Torndeco** [comment]
Makes zero sense

extDB is an extension that is loaded by ArmaServer
RCon feature connects to the ArmaServer which is local i.e 127.0.0.1

If you can't connect to a local ip then you have an issue with your server setup.
There really is no need to connect to any other IP except for local pc.

**Comment by killerty69** [comment]
It has something to do with vilayer, I realize it seems stupid. I will just fix it myself, just wanted to make you aware.

**Comment by Torndeco** [comment]
https://github.com/Torndeco/extdb/blob/stable/src/ext.cpp#L421

Change to 
bercon.updateLogin(pConf->getInt((rcon_conf + ".IP"), "127.0.0.1"), pConf->getInt((rcon_conf + ".Port"), 2302), pConf->getString((rcon_conf + ".Password"), "password"));

Should do the trick, you then be able to define the IP in the config file.

Villayer prob has some sort of VM setup

**Comment by killerty69** [comment]
Got it sir, thank you very much.
