### ISSUE TITLE
Improve: Rcon Code (Reserved Slots / Warnings)

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/extdb#16]
Atm, its based off bercon, hacked together abit using exceptional handling to keep connection alive.

Need to improve code & hopefully add the following.
Reserved Slots Support to extension && Possible Warning Messages Output i.e for errors.
Configurable via config files

**Comment by Torndeco** [comment]
Currently RCon code is enabled in extension.
It just needs some testing etc...

Still need to code the logic for keeping track of player counts + reserved slots etc

**Comment by Colonelfury** [comment]
Quick question, is there a new link to the already compiled files? I could not find them. Thanks!

**Comment by Torndeco** [comment]
https://github.com/Torndeco/extdb/releases

**Comment by Colonelfury** [comment]
I have went there, and just downloaded newest version, however I still cannot find the @extDB already compiled files, and when you go to readme then wiki, there is a link to compiled, however the link does not work.

**Comment by Torndeco** [comment]
Wiki is outof date seriously
https://github.com/Torndeco/extdb/releases

Download the windows.rar or linux.rar for a release

**Comment by Colonelfury** [comment]
Thank you very much, and thanks for all your hard work on this add on, by far the best database

**Comment by Torndeco** [comment]
Closing this....
This can now be implemented in SQF Code using onPlayerConnected
Which allows for better implementation i.e in-game GUI explaining why to the Player

Or allow to add code to allow reserved slots for Steam Friends etc...
