### ISSUE TITLE
DB_CUSTOM_V5: Add Support for MySQL Insert ID

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/extdb#85]

**Comment by ste93cry** [comment]
:+1: it would be really useful to have it

**Comment by Lict0r** [comment]
I would be using it. At the moment I am retrieving the insert id by another DB_RAW call.

**Comment by Torndeco** [comment]
This feature (workaround anyways) is added in https://github.com/Torndeco/extdb2
Also all offical future dev is on extDB2
