### ISSUE TITLE
Memory Leakage

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/extdb#95]
Leaking Memory somewhere in extDB + extDB2
Memory Allocator is ok
ASIO Threads are ok

Seems to happen when querying Database...

Notes:
Butcher extDB + make sure custom changes to Poco Session Pool arent to blame
Need to run extDB through valgrind + memcheck

**Comment by Torndeco** [comment]
fixed in v27
Recommed people update if using v22->26

**Comment by RimBlock** [comment]
Still building with v21 so have not seen the issue :-).  

Will move to v27+ shorly.

Thanks
